services:
  telegraf:
    container_name: telegraf
    hostname: telegraf
    image: telegraf:1.27
    restart: unless-stopped
    volumes:
      - /docker/telegraf/conf/telegraf.d:/etc/telegraf/telegraf.d:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /docker/influxdb2/data/bucket_du.txt:/influxdb2/bucket_du.txt:ro
      - /:/hostfs:ro
      - /docker/telegraf/bin/aq.star:/usr/local/bin/aq.star:ro
      - /docker/telegraf/bin/airnow.star:/usr/local/bin/airnow.star:ro
      - /docker/telegraf/bin/bucket_du.sh:/usr/local/bin/bucket_du.sh:ro
    env_file:
      - env_file_secret
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
    command: --config-directory /etc/telegraf/telegraf.d
