services:
  nodered:
    container_name: mynodered
    hostname: nodered
    image: nodered/node-red:3.0.2
    restart: unless-stopped
    volumes:
      - /docker/nodered/data:/data
    ports:
      - 1880:1880
