
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

#automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

alarm_control_panel:
  - platform: manual
    name: "Home Alarm"
    code: ""
    arming_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

automation:
  - alias: 'Trigger alarm while armed away'
    trigger:
      - platform: state
        entity_id: binary_sensor.back_door
        to: "active"
    condition:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: arm_away
    action:
      service: alarm_control_panel.alarm_trigger
      target:
        entity_id: alarm_control_panel.home_alarm
  - alias: 'Send notification when alarm triggered'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "triggered"
    action:
      - service: notify.notify
        data:
          message: "ALARM! The alarm has been triggered"
  - alias: 'Send notification when alarm is Disarmed'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "disarmed"
    action:
      - service: notify.notify
        data:
          message: "ALARM! The alarm is Disarmed at {{ states('sensor.date_time') }}"

mqtt:
  sensor: !include_dir_merge_list mqtt/sensor

  binary_sensor: !include_dir_merge_list mqtt/binary_sensor
