    - unique_id: mbr_temp
      state_topic: "influx/Owens/sensors/#"
      name: Master BR temperature
      unit_of_measurement: 'F'
      value_template: >
        {% if value.split(',')[1].split('=')[1] == 'SCD40' and value.split(',')[3].split('=')[1] == 'mbr' and value.split(',')[4].split(' ')[0].split('=')[1] == 'door' %}
          {{ value.split(' ')[1].split(',')[1].split('=')[1] }}
        {% endif %}

    - unique_id: mbr_humidity
      state_topic: "influx/Owens/sensors/#"
      name: Master BR humidity
      unit_of_measurement: '%'
      value_template: >
        {% if value.split(',')[1].split('=')[1] == 'SCD40' and value.split(',')[3].split('=')[1] == 'mbr' and value.split(',')[4].split(' ')[0].split('=')[1] == 'door' %}
          {{ value.split(' ')[1].split(',')[2].split('=')[1] }}
        {% endif %}

    - unique_id: mbr_co2
      state_topic: "influx/Owens/sensors/#"
      name: Master BR CO2
      unit_of_measurement: 'ppm'
      value_template: >
        {% if value.split(',')[1].split('=')[1] == 'SCD40' and value.split(',')[3].split('=')[1] == 'mbr' and value.split(',')[4].split(' ')[0].split('=')[1] == 'door' %}
          {{ value.split(' ')[1].split(',')[0].split('=')[1] }}
        {% endif %}

    - unique_id: mbr_light
      state_topic: "influx/Owens/sensors/#"
      name: Master BR light
      value_template: >
        {% if value.split(',')[1].split('=')[1] == 'funhouse' and value.split(',')[3].split('=')[1] == 'mbr' and value.split(',')[4].split(' ')[0].split('=')[1] == 'door' %}
          {{ value.split(' ')[1].split('=')[1] }}
        {% endif %}

    - unique_id: mbr_tvoc
      state_topic: "influx/Owens/sensors/#"
      name: Master BR TVOC
      unit_of_measurement: 'ppm'
      value_template: >
        {% if value.split(',')[1].split('=')[1] == 'SGP30' and value.split(' ')[1].split('=')[0] == 'tvoc' and value.split(',')[3].split('=')[1] == 'mbr' and value.split(',')[4].split(' ')[0].split('=')[1] == 'door' %}
          {{ value.split(' ')[1].split('=')[1] }}
        {% endif %}

    - unique_id: basement_dc_temp
      state_topic: "Owens/sensors/basement/dc/temp_F"
      name: Basement DC temperature
      unit_of_measurement: 'F'

    - unique_id: basement_dc_humidity
      state_topic: "Owens/sensors/basement/dc/rel_humidity"
      name: Basement DC humidity
      unit_of_measurement: '%'

    - unique_id: garage_temp
      state_topic: "Owens/sensors/garage/back/temp_F"
      name: Garage temperature
      unit_of_measurement: 'F'

    - unique_id: garage_humidity
      state_topic: "Owens/sensors/garage/back/rel_humidity"
      name: Garage humidity
      unit_of_measurement: '%'

    - unique_id: mbr_pm1.0
      state_topic: "influx/Owens/sensors/#"
      name: Master BR PM1.0
      unit_of_measurement: 'ug/m3'
      value_template: >
        {% if value.split(',')[1].split('=')[1] == 'PMSA003i' and value.split(',')[3].split('=')[1] == 'mbr' and value.split(',')[4].split(' ')[0].split('=')[1] == 'door' %}
          {{ value.split(' ')[1].split(',')[3].split('=')[1] }}
        {% endif %}

    - unique_id: mbr_pm2.5
      state_topic: "influx/Owens/sensors/#"
      name: Master BR PM2.5
      unit_of_measurement: 'ug/m3'
      value_template: >
        {% if value.split(',')[1].split('=')[1] == 'PMSA003i' and value.split(',')[3].split('=')[1] == 'mbr' and value.split(',')[4].split(' ')[0].split('=')[1] == 'door' %}
          {{ value.split(' ')[1].split(',')[4].split('=')[1] }}
        {% endif %}

    - unique_id: mbr_pm10.0
      state_topic: "influx/Owens/sensors/#"
      name: Master BR PM10.0
      unit_of_measurement: 'ug/m3'
      value_template: >
        {% if value.split(',')[1].split('=')[1] == 'PMSA003i' and value.split(',')[3].split('=')[1] == 'mbr' and value.split(',')[4].split(' ')[0].split('=')[1] == 'door' %}
          {{ value.split(' ')[1].split(',')[5].split('=')[1] }}
        {% endif %}